version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: windi-messenger-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/windi_messenger
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    container_name: windi-messenger-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=windi_messenger
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: